ワークフローのコミットC

diff --git a/.github/workflows/composeLint_example.yml b/.github/workflows/composeLint_example.yml
--- a/.github/workflows/composeLint_example.yml
+++ b/.github/workflows/composeLint_example.yml
@@ -36,8 +36,13 @@ jobs:
         run: ./gradlew lint
 
       - name: Comment via reviewdog
+        if: always()
         run: |
-          cat app/build/reports/android-lint/lintResults.sarif \
-            | reviewdog -f=sarif -reporter=github-pr-check -filter-mode=nofilter -tee -fail-on-error=false
+          FILE=app/build/reports/android-lint/lintResults.sarif
+          if [ -f "$FILE" ]; then
+            cat "$FILE" | reviewdog -f=sarif -reporter=github-pr-check -filter-mode=nofilter -tee -fail-on-error=false || true
+          else
+            echo "SARIF not found"
+          fi
         env:
           REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
